version: '3'

services:
  db:
    build: .
    image: mlunax/mongo-debian:0.0.1
    ports: 
      - 127.0.0.1:27017:27017
    volumes:
      - ./db:/data/db:rw
  client: 
    image: mlunax/mongo-debian:0.0.1
    command: mongo mongodb://db:27017
    depends_on: 
      - db
    