version: '3'

services:
  db:
    build: .
    environment: 
      - START_ARGS= #--auth
    image: mlunax/mongo-debian:0.0.3
    ports: 
      - 127.0.0.1:27017:27017
    volumes:
      - ./db:/data/db
  client: 
    image: mlunax/mongo-debian:0.0.3
    command: mongo mongodb://db:27017
    depends_on: 
      - db
    